parser: babel-eslint

extends:
 - airbnb
 - plugin:import/errors
 - plugin:import/warnings

env:
 browser: true
 node: true

plugins:
 - import

globals:
 gettext: true
 jQuery: true
 $: true
 L: true
 module: true
 process: true
 __dirname: true
 global: true
 window: true
 document: true
 console: true
 ScrollReveal: true
 CountUp: true

parserOptions:
 ecmaVersion: 6
 sourceType: module
 ecmaFeatures:
  jsx: true
  modules: true
  experimentalObjectRestSpread: true

settings:
 react:
   pragma: React
   version: 16.4
 import/resolver:
   node:
     paths: ['src/']
     extensions:
      - .js
      - .jsx

rules:
  arrow-parens: [error, as-needed]
  camelcase: [error, {ignoreDestructuring: true, allow: [^UNSAFE_, first_name, last_name, render_components, ws_protocol]}]
  import/extensions: off
  jsx-a11y/anchor-is-valid: off
  jsx-quotes: [error, prefer-single]
  no-prototype-builtins: off
  object-curly-spacing: [error, never]
  react/jsx-filename-extension: off
  space-before-blocks: [error, {functions: never, keywords: never, classes: always}]
  space-before-function-paren: [error, {anonymous: always, named: never, asyncArrow: always}]
